name: multiplication

services:
  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
