spring.application.name: gateway

server:
  port: 8000

spring.config.import: "consul:"

spring.cloud.consul:
  enabled: true
  ribbon:
    enabled: false
  discovery:
    # get only services that pass health check
    query-passing: true
  config:
    data-key: application.yml
    prefixes: config
    format: yaml
    default-context: defaults

spring.cloud.gateway:
  routes:
    - id: multiplication
      uri: lb://multiplication
      predicates:
        - Path=/challenges/**,/attempts,/attempts/**,/users/**
    - id: gamification
      uri: lb://gamification
      predicates:
        - Path=/leaders
  globalcors:
    cors-configurations:
      '[/**]':
        allowedOrigins: "http://localhost:3000"
        allowedHeaders:
          - "*"
        allowedMethods:
          - "GET"
          - "POST"
          - "OPTIONS"
  default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Origin,RETAIN_UNIQUE
    # retry filter to execute subsequent request, so that the load balancer will
    # route to any healthy instance
    - name: Retry
      args:
        retries: 3
        methods: GET,POST

#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace
